name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *"
    
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate breakout SVG
        uses: cyprieng/github-breakout@v1
        with:
          github_username: yashita72

      - name: Move generated SVGs
        run: |
          mkdir -p images
          mv output/light.svg images/breakout-light.svg
          mv output/dark.svg images/breakout-dark.svg

      - name: Commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add images
          git commit -m "Update breakout SVGs" || echo "No changes"

          git push
